/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *///dd
package portadas;

import basededatos.MySqlConn;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.apache.commons.codec.digest.DigestUtils;
/**
 *
 * @author Cynthia Maritza
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    MySqlConn conn = new MySqlConn();
    private Object DigestUtils;
    public Login() {
        initComponents();
        jTextFieldCuenta.setBackground(new Color(0,0,0,0));
        jTextFieldCuenta.setOpaque(false);
        jTextFieldCuenta.setBorder(null);
       jTextFieldCuenta.setForeground(Color.WHITE);
        
       jPasswordFieldContraseña.setBackground(new Color(0,0,0,0));
       jPasswordFieldContraseña.setOpaque(false);
       jPasswordFieldContraseña.setBorder(null);
       jPasswordFieldContraseña.setForeground(Color.WHITE);
       //jLabelF1.setVisible(true);
       
        //jLabelF2.setVisible(false);
       jPanelFondoPrincipal.setSize(1920,1960);
       
       try {
        //create the font to use. Specify the size!
        Font fuente = Font.createFont(Font.TRUETYPE_FONT, new File("src\\font\\Braxton Free.otf")).deriveFont(60f);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        //register the font
        ge.registerFont(fuente);
        jLabelTitulo.setFont(fuente);
        } catch (IOException e) {
            e.printStackTrace();
        } catch(FontFormatException e) {
            e.printStackTrace();
        }

    
   
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoPrincipal = new PanelIm("src/imagenes/fondop.jpg");
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCuenta = new javax.swing.JLabel();
        jTextFieldCuenta = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Froog Resort");
        setResizable(false);

        jPanelFondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Valle de los Sapos Arcoíris No. 129 Boullevard Martinaisse, Revachol.");
        jPanelFondoPrincipal.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabelCuenta.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuenta.setText("Cuenta:");
        jPanelFondoPrincipal.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 730, 158, 44));

        jTextFieldCuenta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldCuenta.setOpaque(false);
        jTextFieldCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCuentaMouseClicked(evt);
            }
        });
        jTextFieldCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCuentaActionPerformed(evt);
            }
        });
        jPanelFondoPrincipal.add(jTextFieldCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 740, 160, 40));

        jLabelContraseña.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        jPanelFondoPrincipal.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 830, -1, 60));

        jPasswordFieldContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPasswordFieldContraseña.setOpaque(false);
        jPasswordFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordFieldContraseñaMouseClicked(evt);
            }
        });
        jPasswordFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseñaActionPerformed(evt);
            }
        });
        jPanelFondoPrincipal.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 840, 158, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelFondoPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 1010, -1, -1));

        jLabelTitulo1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("Froog Resort");
        jPanelFondoPrincipal.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContraseñaActionPerformed

    private void jTextFieldCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCuentaMouseClicked
        // TODO add your handling code here:
       // jLabelF1.setVisible(true);
        
        //jLabelF2.setVisible(false);

      
        
    }//GEN-LAST:event_jTextFieldCuentaMouseClicked

    private void jPasswordFieldContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaMouseClicked
        // TODO add your handling code here:
        //jLabelF1.setVisible(false);
        //jLabelF2.setVisible(true);
    }//GEN-LAST:event_jPasswordFieldContraseñaMouseClicked

    private void jTextFieldCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCuentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cuenta, contraseña, query;
        cuenta = this.jTextFieldCuenta.getText().trim();
        query = "select * from cuentas where cuenta = "+"'"+cuenta+"'";
        this.conn.Consult(query);
        try{
            String contraseñaMySql = this.conn.rs.getString(2);
            char [] passw = this.jPasswordFieldContraseña.getPassword();
            contraseña = new String(passw);
            String contraseñaencriptada;
            contraseñaencriptada = org.apache.commons.codec.digest.DigestUtils.md5Hex(contraseña);
            System.out.println(contraseñaencriptada);
            if(contraseñaMySql.equals(contraseñaencriptada)){
                JOptionPane.showMessageDialog(this,"Bienvenido "+this.conn.rs.getString(1)+" al sistema.");
                new Menu().setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Error en la contraseña."); 
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"No existe la cuenta");
            System.out.println("No existe la cuenta");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanelFondoPrincipal;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldCuenta;
    // End of variables declaration//GEN-END:variables
class PanelIm extends JPanel {

        private Image fondo;
        private String ruta;
        
        public PanelIm(String ruta){
            this.fondo = null;
            this.ruta = ruta;
        }
        @Override
        public void paint(Graphics g) {
            fondo = new ImageIcon(ruta).getImage();
            g.drawImage(fondo, 0, 0, getWidth(), getHeight(), null);

            setOpaque(false);
            super.paint(g);
        }
    }
}
