/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *///dd
package portadas;

import basededatos.MySqlConn;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.apache.commons.codec.digest.DigestUtils;
/**
 *
 * @author Cynthia Maritza
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    MySqlConn conn = new MySqlConn();
    private Object DigestUtils;
    AudioClip sonido;
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        SonidoLogin();
        
        jTextFieldCuenta.setBackground(new Color(0,0,0,0));
        jTextFieldCuenta.setOpaque(false);
        jTextFieldCuenta.setBorder(null);
        jTextFieldCuenta.setForeground(Color.WHITE);

        jPasswordFieldContraseña.setBackground(new Color(0, 0, 0, 0));
        jPasswordFieldContraseña.setOpaque(false);
        jPasswordFieldContraseña.setBorder(null);
        jPasswordFieldContraseña.setForeground(Color.WHITE);

        jPanelFondoPrincipal.setSize(1051, 665);

        try {
            //create the font to use. Specify the size!
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, new File("src\\font\\Braxton Free.otf")).deriveFont(60f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            //register the font
            ge.registerFont(fuente);
            jLabelTitulo.setFont(fuente);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FontFormatException e) {
            e.printStackTrace();
        }
        

    }
    
    private void SonidoLogin(){
       sonido= java.applet.Applet.newAudioClip(getClass().getResource("/imagenes/Audio.wav"));
       sonido.play(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondoPrincipal = new PanelIm("src/imagenes/fondop.jpg");
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCuenta = new javax.swing.JLabel();
        jTextFieldCuenta = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jButtonIngresar = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Froog Resort");
        setMaximumSize(new java.awt.Dimension(1051, 665));
        setResizable(false);

        jPanelFondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Valle de los Sapos Arcoíris No. 129 Boullevard Martinaisse, Revachol.");
        jPanelFondoPrincipal.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 740, 30));

        jLabelCuenta.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuenta.setText("Cuenta:");
        jPanelFondoPrincipal.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 158, 44));

        jTextFieldCuenta.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTextFieldCuenta.setOpaque(false);
        jPanelFondoPrincipal.add(jTextFieldCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 160, 40));

        jLabelContraseña.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        jPanelFondoPrincipal.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, -1, 60));

        jPasswordFieldContraseña.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jPasswordFieldContraseña.setOpaque(false);
        jPanelFondoPrincipal.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 160, 40));

        jButtonIngresar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanelFondoPrincipal.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, -1, -1));

        jLabelTitulo1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("Froog Resort");
        jPanelFondoPrincipal.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        String cuenta, contraseña, query;
        cuenta = this.jTextFieldCuenta.getText().trim();
        query = "select * from cuentas where cuenta = "+"'"+cuenta+"'";
        this.conn.Consult(query);
        try{
            String contraseñaMySql = this.conn.rs.getString(2);
            char [] passw = this.jPasswordFieldContraseña.getPassword();
            contraseña = new String(passw);
            String contraseñaencriptada;
            contraseñaencriptada = org.apache.commons.codec.digest.DigestUtils.md5Hex(contraseña);
            System.out.println(contraseñaencriptada);
            if(contraseñaMySql.equals(contraseñaencriptada)){
                JOptionPane.showMessageDialog(this,"Bienvenido "+this.conn.rs.getString(1)+" al sistema.");
                new Menu().setVisible(true);
                sonido.stop();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Error en la contraseña."); 
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"No existe la cuenta");
            System.out.println("No existe la cuenta");
        }
        
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanelFondoPrincipal;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldCuenta;
    // End of variables declaration//GEN-END:variables
class PanelIm extends JPanel {

        private Image fondo;
        private String ruta;
        
        public PanelIm(String ruta){
            this.fondo = null;
            this.ruta = ruta;
        }
        @Override
        public void paint(Graphics g) {
            fondo = new ImageIcon(ruta).getImage();
            g.drawImage(fondo, 0, 0, getWidth(), getHeight(), null);

            setOpaque(false);
            super.paint(g);
        }
    }
}
