/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misframes;

import basededatos.MySqlConn;
import java.applet.AudioClip;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


public class galeria extends javax.swing.JInternalFrame {

    /**
     * Creates new form galeria
     */
    AudioClip sonido;
    int count=1;
    int max=0;
    String titles[]={"HABITACION SIMPLE","HABITACION DOBLE","HABITACION TRIPLE","SALA DE ESTAR","BAÑO","AREA RECREATIVA","GIMNASIO","ALBERCA","RESTAURANTE","ZONA DE SPA"};
    MySqlConn cc=new MySqlConn();
    Connection cn=cc.conn;
    public galeria() {
        initComponents();
        sonido= java.applet.Applet.newAudioClip(getClass().getResource("/imagenes/Audio.wav"));
        sonido.play();
        String ruta="";
        
        try {
            
            Statement st;
            ResultSet rs;
            st=cn.createStatement();
            rs=st.executeQuery("SELECT COUNT(*) FROM galeria;");
            while(rs.next()){
                max=rs.getInt(1);
            }
            
            st = cn.createStatement();
            rs=st.executeQuery("SELECT RUTA FROM galeria WHERE ID = 1 ");
            
            while(rs.next()){
                ruta=rs.getString(1);
            }
            System.out.println(ruta);
            System.out.println(System.getProperty("java.class.path"));
            Image aux = new ImageIcon(this.getClass().getResource("/imagenes/"+ruta)).getImage();
            //Image aux=new ImageIcon("/Images/"+ruta).getImage();
            ImageIcon aux2=new ImageIcon(aux);
            
            jLabel1.setIcon(aux2);
            

        } catch (SQLException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, 110, 60));

        jButton2.setText("anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 110, 60));

        jButton3.setText("STOP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 120, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 510, 290));

        jLabel2.setText("HABITACION SIMPLE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 140, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ruta="";
        
        count++;
        
         if(count>max){
             count=1;
         }
         this.jLabel2.setText(titles[count-1]); 
         
         
        try {
            Statement st;
            ResultSet rs;
            
            st = cn.createStatement();
            rs=st.executeQuery("SELECT RUTA FROM galeria WHERE ID = "+count+" ");
            
            while(rs.next()){
                ruta=rs.getString(1);
            }
            System.out.println(ruta);
            Image aux = new ImageIcon(this.getClass().getResource("/imagenes/"+ruta)).getImage();
            ImageIcon aux2=new ImageIcon(aux);
            jLabel1.setIcon(aux2);
            

        } catch (SQLException e) {
                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ruta="";
        
        count--;
        
         if(count<1){
             count=max;
         }
         this.jLabel2.setText(titles[count-1]);  
         
         
        try {
            Statement st;
            ResultSet rs;
            
            st = cn.createStatement();
            rs=st.executeQuery("SELECT RUTA FROM galeria WHERE ID = "+count+" ");
            
            while(rs.next()){
                ruta=rs.getString(1);
            }
            System.out.println(ruta);
            Image aux = new ImageIcon(this.getClass().getResource("/imagenes/"+ruta)).getImage();
            ImageIcon aux2=new ImageIcon(aux);
            jLabel1.setIcon(aux2);
            

        } catch (SQLException e) {
                
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(this.jButton3.getText()=="STOP"){
            sonido.stop();
            this.jButton3.setText("PLAY");
        }else{
            sonido.play();
            this.jButton3.setText("STOP");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
    
    
    
}
